language: go

go:
  - 1.4
  - 1.5
  - 1.6
  - 1.7

os:
  - linux
  - osx

script:
  - go test -v ./...
  - go test -v -race ./...

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/69b57e988266b7fa9abe
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false


